Added persistent score storage and gestion
Aleoris/DRUNK pull request #27
Opened 2021-03-17 04:00 UTC by fmichaut-dev

- Added .vsconfig to gitignore
- Created ScoreManager class
- Added functions to add new scores, list the current ones, and clear the scores
- At startup, load the score list from a file
- All the functions that change the score list write the new content to the disk

2021-03-17 14:34 UTC, ClaudiaLapalme requested changes

2021-03-17 14:34 UTC, ClaudiaLapalme commented on Assets/Code/Scripts/ScoreManager.cs
> +    public class ScoreData
I didn't realize that you could serialize a class. This is very cool and useful for testing

2021-03-17 14:34 UTC, ClaudiaLapalme commented on Assets/Code/Scripts/ScoreManager.cs
> +        foreach (ScoreData score in scores) {
Wouldn't it be more efficient to just check the last value (or first, depending on if it's ascending or descending). I noticed that you already sort when a new high score is entered anyways.

2021-03-17 14:34 UTC, ClaudiaLapalme commented on Assets/Code/Scripts/ScoreManager.cs
> +        scores.Sort((ScoreData a, ScoreData b) => { return a.score - b.score; });
I'm a little confused by the return on this line. What does it do exactly?

2021-03-17 21:52 UTC, fmichaut-dev commented on Assets/Code/Scripts/ScoreManager.cs
> +        foreach (ScoreData score in scores) {
Oh you are right, i didn't think of taking adventage of the sorting 
I think i just need to check if the value is comprised between the first and last values
I'll change that

2021-03-17 21:55 UTC, fmichaut-dev commented on Assets/Code/Scripts/ScoreManager.cs
> +        scores.Sort((ScoreData a, ScoreData b) => { return a.score - b.score; });
It return an integer indicating which value is the biggest. So it return an integer less than, equal to or bigger than 0 following the same convention as in this page : https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.comparer-1.compare?view=net-5.0

2021-03-17 21:57 UTC, fmichaut-dev commented on Assets/Code/Scripts/ScoreManager.cs
> +    public class ScoreData
You can serialize a class, and most of c#'s containers are also serializable, meaning you can serialize a class containing Lists or Disctionary of other classes. Altho, i think there is some restrictions, i don't remember them exactly tho

2021-03-17 23:02 UTC, ClaudiaLapalme approved these changes
great work!

2021-03-19 18:47 UTC, tedgag approved these changes
Looks good! Approved

2021-03-19 18:51 UTC, merged